### PR TITLE
MG-156 - Add domain login middleware

### LINKED ISSUE #156: [BUG] Redirect user to Domain Login before accessing any resources
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What were you trying to achieve?

I was testing Oauth2.0 and proviced an incorrect redirect URL to `http://localhost:9095/` rather than `http://localhost:9095/domains`. 

### What are the expected results?

Since I have not logged in to any domain I should be redirected to domain login page and login first rather than showing the error

### What are the received results?

Error page with somehow incorrect error message
image

### Steps To Reproduce

1. Login with username and password
2. Don't login to the domain
3. Go to `http://localhost:9095/` directly

### In what environment did you encounter the issue?

- brave browser
- running UI as of version https://github.com/absmach/magistrala-ui/commit/128b5152a334019fe94785d8f1a5c97880f80c4f

### Additional information you deem important

One way to solve this would be to inspect the token first and ascertain they have logged in to a domain. If not redirect them to domain login if yes proceed to giving them access on the requested resource

You can use the following json to reply the issue

<details>
<summary>Details</summary>

```json
{
    "title": "issue 156",
    "steps": [
        {
            "type": "setViewport",
            "width": 2030,
            "height": 1003,
            "deviceScaleFactor": 1,
            "isMobile": false,
            "hasTouch": false,
            "isLandscape": false
        },
        {
            "type": "navigate",
            "url": "http://localhost:9095/domains",
            "assertedEvents": [
                {
                    "type": "navigation",
                    "url": "http://localhost:9095/domains",
                    "title": "Domains"
                }
            ]
        },
        {
            "type": "navigate",
            "url": "http://localhost:9095/error?error=failed+to+retrieve+entity",
            "assertedEvents": [
                {
                    "type": "navigation",
                    "url": "http://localhost:9095/error?error=failed+to+retrieve+entity",
                    "title": ""
                }
            ]
        },
        {
            "type": "click",
            "target": "main",
            "selectors": [
                [
                    "aria/Back"
                ],
                [
                    "div.main-content a"
                ],
                [
                    "xpath//html/body/div[3]/div/div/div/div/a"
                ],
                [
                    "pierce/div.main-content a"
                ],
                [
                    "text/Back"
                ]
            ],
            "offsetY": 14.612579345703125,
            "offsetX": 452.78515625
        },
        {
            "type": "navigate",
            "url": "http://localhost:9095/domains",
            "assertedEvents": [
                {
                    "type": "navigation",
                    "url": "http://localhost:9095/domains",
                    "title": "Domains"
                }
            ]
        },
        {
            "type": "click",
            "target": "main",
            "selectors": [
                [
                    "aria/[role=\"button\"]"
                ],
                [
                    "div.itemsTable button"
                ],
                [
                    "xpath//html/body/div[3]/div/div/div/div[2]/div[2]/table/tbody/tr/td[6]/form/button"
                ],
                [
                    "pierce/div.itemsTable button"
                ]
            ],
            "offsetY": 12.2607421875,
            "offsetX": 33.8577880859375,
            "assertedEvents": [
                {
                    "type": "navigation",
                    "url": "http://localhost:9095/?domain=433cd30f-8a6a-42d0-8610-9c63a7512ec2",
                    "title": ""
                }
            ]
        }
    ]
}

```

</details>

### PR DESCRIPTION
**Pull request by ianmuchyri**
# What type of PR is this?

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## What does this do?
Add a domain login middleware that checks the token being used to access a page if it contains the domain field. If it does not the user is redirected to the domains page automatically so that they can log into a domain before proceeding

## Which issue(s) does this PR fix/relate to?

- Related Issue #
- Resolves #156 

## Have you included tests for your changes?

- [ ] Yes
- [x] No, and this is why: 

## Did you document any new/modified functionality?

- [ ] Yes
- [x] No, and this is why:

### CODE REVIEW

File: ui/api/transport.go [hunk 1]
```diff
@@ -2402,6 +2405,29 @@ func TokenMiddleware(next http.Handler) http.Handler {
...
+			return
+		}
+
+		token, _, err := new(jwt.Parser).ParseUnverified(tokenString, jwt.MapClaims{})
+		if err != nil {
+			http.Redirect(w, r, fmt.Sprintf("/%s?error=%s", errorAPIEndpoint, url.QueryEscape(err.Error())), http.StatusSeeOther)
+			return
+		}
+		if claims, ok := token.Claims.(jwt.MapClaims); ok {
+			if claims["domain"] == "" {
```
Comment (dborovcanin) [inline ui/api/transport.go:2422]: Let's go with `if _, ok := claims["domain"]; !ok {...}` since it's a little more go-idimatic (and logically more correct since nothing prevents the map from having an empty value for the key - in the future, we may have single-tenant deployments to use an empty domain).

**Review by dborovcanin — CHANGES_REQUESTED** [review]

**Review by dborovcanin — APPROVED** [review]
